import type { Metadata } from "next";
import "./globals.css";
import { League_Spartan } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import Providers from "@/components/Provider";
import { Toaster } from 'react-hot-toast'



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const intesr = League_Spartan({ subsets: ["latin"], weight: ["400"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={intesr.className}
      >
        <Providers>
          <NextTopLoader color="#FF0000" />
          {children}
          <Toaster position="bottom-right" />
        </Providers>
      </body>
    </html>
  );
}
